New year 2023
knowledgesystems/signal pull request #158
Opened 2023-01-04 02:33 UTC by leexgh

2023-01-05 19:27 UTC, onursumer commented
@leexgh @zhx828 looks like we already have #153 which is also updating the publication link. I guess we can close #153 with a comment referring to this PR, right?

2023-01-05 21:11 UTC, zhx828 requested changes

2023-01-05 21:11 UTC, zhx828 commented on src/components/Footer.tsx
> -                            <div>&copy; 2022 Memorial Sloan Kettering Cancer Center</div>
Can we do `{new Date().getFullYear()}` instead? @leexgh

2023-01-10 20:21 UTC, inodb approved these changes

2023-01-10 23:19 UTC, onursumer approved these changes
Looks good!

2023-01-12 19:39 UTC, merged